<?php
return [
    [ 'code'=> "AF", 'name'=> "أفغانستان", 'nameEn'=> "Afghanistan" ],
    [ 'code'=> "AX", 'name'=> "جزر أولاند", 'nameEn'=> "Åland Islands" ],
    [ 'code'=> "AL", 'name'=> "ألبانيا", 'nameEn'=> "Albania" ],
    [ 'code'=> "DZ", 'name'=> "الجزائر", 'nameEn'=> "Algeria" ],
    [ 'code'=> "AS", 'name'=> "ساموا الأمريكية", 'nameEn'=> "American Samoa" ],
    [ 'code'=> "AD", 'name'=> "أندورا", 'nameEn'=> "Andorra" ],
    [ 'code'=> "AO", 'name'=> "أنغولا", 'nameEn'=> "Angola" ],
    [ 'code'=> "AI", 'name'=> "أنغويلا", 'nameEn'=> "Anguilla" ],
    [ 'code'=> "AQ", 'name'=> "أنتاركتيكا", 'nameEn'=> "Antarctica" ],
    [ 'code'=> "AG", 'name'=> "أنتيغوا وباربودا", 'nameEn'=> "Antigua and Barbuda" ],
    [ 'code'=> "AR", 'name'=> "الأرجنتين", 'nameEn'=> "Argentina" ],
    [ 'code'=> "AM", 'name'=> "أرمينيا", 'nameEn'=> "Armenia" ],
    [ 'code'=> "AW", 'name'=> "أروبا", 'nameEn'=> "Aruba" ],
    [ 'code'=> "AU", 'name'=> "أستراليا", 'nameEn'=> "Australia" ],
    [ 'code'=> "AT", 'name'=> "النمسا", 'nameEn'=> "Austria" ],
    [ 'code'=> "AZ", 'name'=> "أذربيجان", 'nameEn'=> "Azerbaijan" ],
    [ 'code'=> "BS", 'name'=> "البهاما", 'nameEn'=> "Bahamas" ],
    [ 'code'=> "BH", 'name'=> "البحرين", 'nameEn'=> "Bahrain" ],
    [ 'code'=> "BD", 'name'=> "بنغلاديش", 'nameEn'=> "Bangladesh" ],
    [ 'code'=> "BB", 'name'=> "بربادوس", 'nameEn'=> "Barbados" ],
    [ 'code'=> "BY", 'name'=> "بيلاروس", 'nameEn'=> "Belarus" ],
    [ 'code'=> "BE", 'name'=> "بلجيكا", 'nameEn'=> "Belgium" ],
    [ 'code'=> "BZ", 'name'=> "بليز", 'nameEn'=> "Belize" ],
    [ 'code'=> "BJ", 'name'=> "بنين", 'nameEn'=> "Benin" ],
    [ 'code'=> "BM", 'name'=> "برمودا", 'nameEn'=> "Bermuda" ],
    [ 'code'=> "BT", 'name'=> "بوتان", 'nameEn'=> "Bhutan" ],
    [ 'code'=> "BO", 'name'=> "بوليفيا", 'nameEn'=> "Bolivia" ],
    [ 'code'=> "BQ", 'name'=> "الجزر الكاريبية الهولندية", 'nameEn'=> "Bonaire, Sint Eustatius and Saba" ],
    [ 'code'=> "BA", 'name'=> "البوسنة والهرسك", 'nameEn'=> "Bosnia and Herzegovina" ],
    [ 'code'=> "BW", 'name'=> "بوتسوانا", 'nameEn'=> "Botswana" ],
    [ 'code'=> "BV", 'name'=> "جزيرة بوفيه", 'nameEn'=> "Bouvet Island" ],
    [ 'code'=> "BR", 'name'=> "البرازيل", 'nameEn'=> "Brazil" ],
    [ 'code'=> "IO", 'name'=> "الإقليم البريطاني في المحيط الهندي", 'nameEn'=> "British Indian Ocean Territory" ],
    [ 'code'=> "BN", 'name'=> "بروناي", 'nameEn'=> "Brunei Darussalam" ],
    [ 'code'=> "BG", 'name'=> "بلغارia", 'nameEn'=> "Bulgaria" ],
    [ 'code'=> "BF", 'name'=> "بوركينا فاسو", 'nameEn'=> "Burkina Faso" ],
    [ 'code'=> "BI", 'name'=> "بوروندي", 'nameEn'=> "Burundi" ],
    [ 'code'=> "CV", 'name'=> "الرأس الأخضر", 'nameEn'=> "Cabo Verde" ],
    [ 'code'=> "KH", 'name'=> "كمبوديا", 'nameEn'=> "Cambodia" ],
    [ 'code'=> "CM", 'name'=> "الكاميرون", 'nameEn'=> "Cameroon" ],
    [ 'code'=> "CA", 'name'=> "كندا", 'nameEn'=> "Canada" ],
    [ 'code'=> "KY", 'name'=> "جزر كايمان", 'nameEn'=> "Cayman Islands" ],
    [ 'code'=> "CF", 'name'=> "جمهورية أفريقيا الوسطى", 'nameEn'=> "Central African Republic" ],
    [ 'code'=> "TD", 'name'=> "تشاد", 'nameEn'=> "Chad" ],
    [ 'code'=> "CL", 'name'=> "تشيلي", 'nameEn'=> "Chile" ],
    [ 'code'=> "CN", 'name'=> "الصين", 'nameEn'=> "China" ],
    [ 'code'=> "CX", 'name'=> "جزيرة الكريسماس", 'nameEn'=> "Christmas Island" ],
    [ 'code'=> "CC", 'name'=> "جزر كوكوس", 'nameEn'=> "Cocos (Keeling) Islands" ],
    [ 'code'=> "CO", 'name'=> "كولومبيا", 'nameEn'=> "Colombia" ],
    [ 'code'=> "KM", 'name'=> "جزر القمر", 'nameEn'=> "Comoros" ],
    [ 'code'=> "CG", 'name'=> "الكونغو", 'nameEn'=> "Congo" ],
    [ 'code'=> "CD", 'name'=> "جمهورية الكونغو الديمقراطية", 'nameEn'=> "Congo, Democratic Republic of the" ],
    [ 'code'=> "CK", 'name'=> "جزر كوك", 'nameEn'=> "Cook Islands" ],
    [ 'code'=> "CR", 'name'=> "كوستاريكا", 'nameEn'=> "Costa Rica" ],
    [ 'code'=> "CI", 'name'=> "ساحل العاج", 'nameEn'=> "Côte d'Ivoire" ],
    [ 'code'=> "HR", 'name'=> "كرواتيا", 'nameEn'=> "Croatia" ],
    [ 'code'=> "CU", 'name'=> "كوبا", 'nameEn'=> "Cuba" ],
    [ 'code'=> "CW", 'name'=> "كوراساو", 'nameEn'=> "Curaçao" ],
    [ 'code'=> "CY", 'name'=> "قبرص", 'nameEn'=> "Cyprus" ],
    [ 'code'=> "CZ", 'name'=> "التشيك", 'nameEn'=> "Czechia" ],
    [ 'code'=> "DK", 'name'=> "الدنمارك", 'nameEn'=> "Denmark" ],
    [ 'code'=> "DJ", 'name'=> "جيبوتي", 'nameEn'=> "Djibouti" ],
    [ 'code'=> "DM", 'name'=> "دومينيكا", 'nameEn'=> "Dominica" ],
    [ 'code'=> "DO", 'name'=> "جمهورية الدومينيكان", 'nameEn'=> "Dominican Republic" ],
    [ 'code'=> "EC", 'name'=> "الإكوادور", 'nameEn'=> "Ecuador" ],
    [ 'code'=> "EG", 'name'=> "مصر", 'nameEn'=> "Egypt" ],
    [ 'code'=> "SV", 'name'=> "السلفادور", 'nameEn'=> "El Salvador" ],
    [ 'code'=> "GQ", 'name'=> "غينيا الاستوائية", 'nameEn'=> "Equatorial Guinea" ],
    [ 'code'=> "ER", 'name'=> "إريتريا", 'nameEn'=> "Eritrea" ],
    [ 'code'=> "EE", 'name'=> "إستونيا", 'nameEn'=> "Estonia" ],
    [ 'code'=> "SZ", 'name'=> "إسواتيني", 'nameEn'=> "Eswatini" ],
    [ 'code'=> "ET", 'name'=> "إثيوبيا", 'nameEn'=> "Ethiopia" ],
    [ 'code'=> "FK", 'name'=> "جزر فوكلاند", 'nameEn'=> "Falkland Islands (Malvinas)" ],
    [ 'code'=> "FO", 'name'=> "جزر فارو", 'nameEn'=> "Faroe Islands" ],
    [ 'code'=> "FJ", 'name'=> "فيجي", 'nameEn'=> "Fiji" ],
    [ 'code'=> "FI", 'name'=> "فنلندا", 'nameEn'=> "Finland" ],
    [ 'code'=> "FR", 'name'=> "فرنسا", 'nameEn'=> "France" ],
    [ 'code'=> "GF", 'name'=> "غويانا الفرنسية", 'nameEn'=> "French Guiana" ],
    [ 'code'=> "PF", 'name'=> "بولينيزيا الفرنسية", 'nameEn'=> "French Polynesia" ],
    [ 'code'=> "TF", 'name'=> "الأقاليم الجنوبية الفرنسية", 'nameEn'=> "French Southern Territories" ],
    [ 'code'=> "GA", 'name'=> "الغابون", 'nameEn'=> "Gabon" ],
    [ 'code'=> "GM", 'name'=> "غامبيا", 'nameEn'=> "Gambia" ],
    [ 'code'=> "GE", 'name'=> "جورجيا", 'nameEn'=> "Georgia" ],
    [ 'code'=> "DE", 'name'=> "ألمانيا", 'nameEn'=> "Germany" ],
    [ 'code'=> "GH", 'name'=> "غانا", 'nameEn'=> "Ghana" ],
    [ 'code'=> "GI", 'name'=> "جبل طارق", 'nameEn'=> "Gibraltar" ],
    [ 'code'=> "GR", 'name'=> "اليونان", 'nameEn'=> "Greece" ],
    [ 'code'=> "GL", 'name'=> "جرينلاند", 'nameEn'=> "Greenland" ],
    [ 'code'=> "GD", 'name'=> "غرينادا", 'nameEn'=> "Grenada" ],
    [ 'code'=> "GP", 'name'=> "غوادلوب", 'nameEn'=> "Guadeloupe" ],
    [ 'code'=> "GU", 'name'=> "غوام", 'nameEn'=> "Guam" ],
    [ 'code'=> "GT", 'name'=> "غواتيمالا", 'nameEn'=> "Guatemala" ],
    [ 'code'=> "GG", 'name'=> "غيرنزي", 'nameEn'=> "Guernsey" ],
    [ 'code'=> "GN", 'name'=> "غينيا", 'nameEn'=> "Guinea" ],
    [ 'code'=> "GW", 'name'=> "غينيا بيساو", 'nameEn'=> "Guinea-Bissau" ],
    [ 'code'=> "GY", 'name'=> "غيانا", 'nameEn'=> "Guyana" ],
    [ 'code'=> "HT", 'name'=> "هايتي", 'nameEn'=> "Haiti" ],
    [ 'code'=> "HM", 'name'=> "جزيرة هيرد وجزر ماكدونالد", 'nameEn'=> "Heard Island and McDonald Islands" ],
    [ 'code'=> "VA", 'name'=> "الفاتيكان", 'nameEn'=> "Holy See" ],
    [ 'code'=> "HN", 'name'=> "هندوراس", 'nameEn'=> "Honduras" ],
    [ 'code'=> "HK", 'name'=> "هونغ كونغ", 'nameEn'=> "Hong Kong" ],
    [ 'code'=> "HU", 'name'=> "هنغاريا", 'nameEn'=> "Hungary" ],
    [ 'code'=> "IS", 'name'=> "آيسلندا", 'nameEn'=> "Iceland" ],
    [ 'code'=> "IN", 'name'=> "الهند", 'nameEn'=> "India" ],
    [ 'code'=> "ID", 'name'=> "إندونيسيا", 'nameEn'=> "Indonesia" ],
    [ 'code'=> "IR", 'name'=> "إيران", 'nameEn'=> "Iran (Islamic Republic of)" ],
    [ 'code'=> "IQ", 'name'=> "العراق", 'nameEn'=> "Iraq" ],
    [ 'code'=> "IE", 'name'=> "أيرلندا", 'nameEn'=> "Ireland" ],
    [ 'code'=> "IM", 'name'=> "جزيرة مان", 'nameEn'=> "Isle of Man" ],
    [ 'code'=> "IL", 'name'=> "إسرائيل", 'nameEn'=> "Israel" ],
    [ 'code'=> "IT", 'name'=> "إيطاليا", 'nameEn'=> "Italy" ],
    [ 'code'=> "JM", 'name'=> "جامايكا", 'nameEn'=> "Jamaica" ],
    [ 'code'=> "JP", 'name'=> "اليابان", 'nameEn'=> "Japan" ],
    [ 'code'=> "JE", 'name'=> "جيرسي", 'nameEn'=> "Jersey" ],
    [ 'code'=> "JO", 'name'=> "الأردن", 'nameEn'=> "Jordan" ],
    [ 'code'=> "KZ", 'name'=> "كازاخستان", 'nameEn'=> "Kazakhstan" ],
    [ 'code'=> "KE", 'name'=> "كينيا", 'nameEn'=> "Kenya" ],
    [ 'code'=> "KI", 'name'=> "كيريباتي", 'nameEn'=> "Kiribati" ],
    [ 'code'=> "KP", 'name'=> "كوريا الشمالية", 'nameEn'=> "Korea (Democratic People's Republic of)" ],
    [ 'code'=> "KR", 'name'=> "كوريا الجنوبية", 'nameEn'=> "Korea, Republic of" ],
    [ 'code'=> "KW", 'name'=> "الكويت", 'nameEn'=> "Kuwait" ],
    [ 'code'=> "KG", 'name'=> "قيرغيزستان", 'nameEn'=> "Kyrgyzstan" ],
    [ 'code'=> "LA", 'name'=> "لاوس", 'nameEn'=> "Lao People's Democratic Republic" ],
    [ 'code'=> "LV", 'name'=> "لاتفيا", 'nameEn'=> "Latvia" ],
    [ 'code'=> "LB", 'name'=> "لبنان", 'nameEn'=> "Lebanon" ],
    [ 'code'=> "LS", 'name'=> "ليسوتو", 'nameEn'=> "Lesotho" ],
    [ 'code'=> "LR", 'name'=> "ليبيريا", 'nameEn'=> "Liberia" ],
    [ 'code'=> "LY", 'name'=> "ليبيا", 'nameEn'=> "Libya" ],
    [ 'code'=> "LI", 'name'=> "ليختنشتاين", 'nameEn'=> "Liechtenstein" ],
    [ 'code'=> "LT", 'name'=> "ليتوانيا", 'nameEn'=> "Lithuania" ],
    [ 'code'=> "LU", 'name'=> "لوكسمبورغ", 'nameEn'=> "Luxembourg" ],
    [ 'code'=> "MO", 'name'=> "ماكاو", 'nameEn'=> "Macao" ],
    [ 'code'=> "MG", 'name'=> "مدغشقر", 'nameEn'=> "Madagascar" ],
    [ 'code'=> "MW", 'name'=> "مالاوي", 'nameEn'=> "Malawi" ],
    [ 'code'=> "MY", 'name'=> "ماليزيا", 'nameEn'=> "Malaysia" ],
    [ 'code'=> "MV", 'name'=> "جزر المالديف", 'nameEn'=> "Maldives" ],
    [ 'code'=> "ML", 'name'=> "مالي", 'nameEn'=> "Mali" ],
    [ 'code'=> "MT", 'name'=> "مالطا", 'nameEn'=> "Malta" ],
    [ 'code'=> "MH", 'name'=> "جزر مارشال", 'nameEn'=> "Marshall Islands" ],
    [ 'code'=> "MQ", 'name'=> "مارتينيك", 'nameEn'=> "Martinique" ],
    [ 'code'=> "MR", 'name'=> "موريتانيا", 'nameEn'=> "Mauritania" ],
    [ 'code'=> "MU", 'name'=> "موريشيوس", 'nameEn'=> "Mauritius" ],
    [ 'code'=> "YT", 'name'=> "مايوت", 'nameEn'=> "Mayotte" ],
    [ 'code'=> "MX", 'name'=> "المكسيك", 'nameEn'=> "Mexico" ],
    [ 'code'=> "FM", 'name'=> "ميكرونيزيا", 'nameEn'=> "Micronesia (Federated States of)" ],
    [ 'code'=> "MD", 'name'=> "مولدوفا", 'nameEn'=> "Moldova, Republic of" ],
    [ 'code'=> "MC", 'name'=> "موناكو", 'nameEn'=> "Monaco" ],
    [ 'code'=> "MN", 'name'=> "منغوليا", 'nameEn'=> "Mongolia" ],
    [ 'code'=> "ME", 'name'=> "الجبل الأسود", 'nameEn'=> "Montenegro" ],
    [ 'code'=> "MS", 'name'=> "مونتسرات", 'nameEn'=> "Montserrat" ],
    [ 'code'=> "MA", 'name'=> "المغرب", 'nameEn'=> "Morocco" ],
    [ 'code'=> "MZ", 'name'=> "موزمبيق", 'nameEn'=> "Mozambique" ],
    [ 'code'=> "MM", 'name'=> "ميانمار", 'nameEn'=> "Myanmar" ],
    [ 'code'=> "NA", 'name'=> "ناميبيا", 'nameEn'=> "Namibia" ],
    [ 'code'=> "NR", 'name'=> "ناورو", 'nameEn'=> "Nauru" ],
    [ 'code'=> "NP", 'name'=> "نيبال", 'nameEn'=> "Nepal" ],
    [ 'code'=> "NL", 'name'=> "هولندا", 'nameEn'=> "Netherlands" ],
    [ 'code'=> "NC", 'name'=> "كاليدونيا الجديدة", 'nameEn'=> "New Caledonia" ],
    [ 'code'=> "NZ", 'name'=> "نيوزيلندا", 'nameEn'=> "New Zealand" ],
    [ 'code'=> "NI", 'name'=> "نيكاراغوا", 'nameEn'=> "Nicaragua" ],
    [ 'code'=> "NE", 'name'=> "النيجر", 'nameEn'=> "Niger" ],
    [ 'code'=> "NG", 'name'=> "نيجيريا", 'nameEn'=> "Nigeria" ],
    [ 'code'=> "NU", 'name'=> "نيوي", 'nameEn'=> "Niue" ],
    [ 'code'=> "NF", 'name'=> "جزيرة نورفولك", 'nameEn'=> "Norfolk Island" ],
    [ 'code'=> "MK", 'name'=> "مقدونيا الشمالية", 'nameEn'=> "North Macedonia" ],
    [ 'code'=> "MP", 'name'=> "جزر ماريانا الشمالية", 'nameEn'=> "Northern Mariana Islands" ],
    [ 'code'=> "NO", 'name'=> "النرويج", 'nameEn'=> "Norway" ],
    [ 'code'=> "OM", 'name'=> "عمان", 'nameEn'=> "Oman" ],
    [ 'code'=> "PK", 'name'=> "باكستان", 'nameEn'=> "Pakistan" ],
    [ 'code'=> "PW", 'name'=> "بالاو", 'nameEn'=> "Palau" ],
    [ 'code'=> "PS", 'name'=> "فلسطين", 'nameEn'=> "Palestine, State of" ],
    [ 'code'=> "PA", 'name'=> "بنما", 'nameEn'=> "Panama" ],
    [ 'code'=> "PG", 'name'=> "بابوا غينيا الجديدة", 'nameEn'=> "Papua New Guinea" ],
    [ 'code'=> "PY", 'name'=> "باراغواي", 'nameEn'=> "Paraguay" ],
    [ 'code'=> "PE", 'name'=> "بيرو", 'nameEn'=> "Peru" ],
    [ 'code'=> "PH", 'name'=> "الفلبين", 'nameEn'=> "Philippines" ],
    [ 'code'=> "PN", 'name'=> "جزر بيتكيرن", 'nameEn'=> "Pitcairn" ],
    [ 'code'=> "PL", 'name'=> "بولندا", 'nameEn'=> "Poland" ],
    [ 'code'=> "PT", 'name'=> "البرتغال", 'nameEn'=> "Portugal" ],
    [ 'code'=> "PR", 'name'=> "بورتوريكo", 'nameEn'=> "Puerto Rico" ],
    [ 'code'=> "QA", 'name'=> "قطر", 'nameEn'=> "Qatar" ],
    [ 'code'=> "RE", 'name'=> "ريونيون", 'nameEn'=> "Réunion" ],
    [ 'code'=> "RO", 'name'=> "رومانيا", 'nameEn'=> "Romania" ],
    [ 'code'=> "RU", 'name'=> "روسيا", 'nameEn'=> "Russia" ],
    [ 'code'=> "RW", 'name'=> "رواندا", 'nameEn'=> "Rwanda" ],
    [ 'code'=> "BL", 'name'=> "سان بارتليمي", 'nameEn'=> "Saint Barthélemy" ],
    [ 'code'=> "SH", 'name'=> "سانت هيلينا", 'nameEn'=> "Saint Helena, Ascension and Tristan da Cunha" ],
    [ 'code'=> "KN", 'name'=> "سانت كيتس ونيفيس", 'nameEn'=> "Saint Kitts and Nevis" ],
    [ 'code'=> "LC", 'name'=> "سانت لوسيا", 'nameEn'=> "Saint Lucia" ],
    [ 'code'=> "MF", 'name'=> "سانت مارتن", 'nameEn'=> "Saint Martin (French part)" ],
    [ 'code'=> "PM", 'name'=> "سان بيير وميكلون", 'nameEn'=> "Saint Pierre and Miquelon" ],
    [ 'code'=> "VC", 'name'=> "سانت فنسنت والغرينادين", 'nameEn'=> "Saint Vincent and the Grenadines" ],
    [ 'code'=> "WS", 'name'=> "ساموا", 'nameEn'=> "Samoa" ],
    [ 'code'=> "SM", 'name'=> "سان مارينو", 'nameEn'=> "San Marino" ],
    [ 'code'=> "ST", 'name'=> "ساو تومي وبرينسيب", 'nameEn'=> "Sao Tome and Principe" ],
    [ 'code'=> "SA", 'name'=> "السعودية", 'nameEn'=> "Saudi Arabia" ],
    [ 'code'=> "SN", 'name'=> "السنغال", 'nameEn'=> "Senegal" ],
    [ 'code'=> "RS", 'name'=> "صربيا", 'nameEn'=> "Serbia" ],
    [ 'code'=> "SC", 'name'=> "سيشل", 'nameEn'=> "Seychelles" ],
    [ 'code'=> "SL", 'name'=> "سيراليون", 'nameEn'=> "Sierra Leone" ],
    [ 'code'=> "SG", 'name'=> "سنغافورة", 'nameEn'=> "Singapore" ],
    [ 'code'=> "SX", 'name'=> "سينت مارتن", 'nameEn'=> "Sint Maarten (Dutch part)" ],
    [ 'code'=> "SK", 'name'=> "سلوفاكيا", 'nameEn'=> "Slovakia" ],
    [ 'code'=> "SI", 'name'=> "سلوفينيا", 'nameEn'=> "Slovenia" ],
    [ 'code'=> "SB", 'name'=> "جزر سليمان", 'nameEn'=> "Solomon Islands" ],
    [ 'code'=> "SO", 'name'=> "الصومال", 'nameEn'=> "Somalia" ],
    [ 'code'=> "ZA", 'name'=> "جنوب أفريقيا", 'nameEn'=> "South Africa" ],
    [ 'code'=> "GS", 'name'=> "جورجيا الجنوبية وجزر ساندويتش الجنوبية", 'nameEn'=> "South Georgia and the South Sandwich Islands" ],
    [ 'code'=> "SS", 'name'=> "جنوب السودان", 'nameEn'=> "South Sudan" ],
    [ 'code'=> "ES", 'name'=> "إسبانيا", 'nameEn'=> "Spain" ],
    [ 'code'=> "LK", 'name'=> "سريلانكا", 'nameEn'=> "Sri Lanka" ],
    [ 'code'=> "SD", 'name'=> "السودان", 'nameEn'=> "Sudan" ],
    [ 'code'=> "SR", 'name'=> "سورينام", 'nameEn'=> "Suriname" ],
    [ 'code'=> "SJ", 'name'=> "سفالبارد ويان ماين", 'nameEn'=> "Svalbard and Jan Mayen" ],
    [ 'code'=> "SE", 'name'=> "السويد", 'nameEn'=> "Sweden" ],
    [ 'code'=> "CH", 'name'=> "سويسرا", 'nameEn'=> "Switzerland" ],
    [ 'code'=> "SY", 'name'=> "سوريا", 'nameEn'=> "Syrian Arab Republic" ],
    [ 'code'=> "TW", 'name'=> "تايوان", 'nameEn'=> "Taiwan, Province of China" ],
    [ 'code'=> "TJ", 'name'=> "طاجيكستان", 'nameEn'=> "Tajikistan" ],
    [ 'code'=> "TZ", 'name'=> "تنزانيا", 'nameEn'=> "Tanzania, United Republic of" ],
    [ 'code'=> "TH", 'name'=> "تايلاند", 'nameEn'=> "Thailand" ],
    [ 'code'=> "TL", 'name'=> "تيمور الشرقية", 'nameEn'=> "Timor-Leste" ],
    [ 'code'=> "TG", 'name'=> "توغو", 'nameEn'=> "Togo" ],
    [ 'code'=> "TK", 'name'=> "توكيلau", 'nameEn'=> "Tokelau" ],
    [ 'code'=> "TO", 'name'=> "تونغا", 'nameEn'=> "Tonga" ],
    [ 'code'=> "TT", 'name'=> "ترينيداد وتوباغو", 'nameEn'=> "Trinidad and Tobago" ],
    [ 'code'=> "TN", 'name'=> "تونس", 'nameEn'=> "Tunisia" ],
    [ 'code'=> "TR", 'name'=> "تركيا", 'nameEn'=> "Turkey" ],
    [ 'code'=> "TM", 'name'=> "تركمانستان", 'nameEn'=> "Turkmenistan" ],
    [ 'code'=> "TC", 'name'=> "جزر توركس وكايكوس", 'nameEn'=> "Turks and Caicos Islands" ],
    [ 'code'=> "TV", 'name'=> "توفالو", 'nameEn'=> "Tuvalu" ],
    [ 'code'=> "UG", 'name'=> "أوغندا", 'nameEn'=> "Uganda" ],
    [ 'code'=> "UA", 'name'=> "أوكرانيا", 'nameEn'=> "Ukraine" ],
    [ 'code'=> "AE", 'name'=> "الإمارات العربية المتحدة", 'nameEn'=> "United Arab Emirates" ],
    [ 'code'=> "GB", 'name'=> "المملكة المتحدة", 'nameEn'=> "United Kingdom of Great Britain and Northern Ireland" ],
    [ 'code'=> "US", 'name'=> "الولايات المتحدة", 'nameEn'=> "United States of America" ],
    [ 'code'=> "UM", 'name'=> "جزر الولايات المتحدة الصغيرة النائية", 'nameEn'=> "United States Minor Outlying Islands" ],
    [ 'code'=> "UY", 'name'=> "أوروغواي", 'nameEn'=> "Uruguay" ],
    [ 'code'=> "UZ", 'name'=> "أوزبكستان", 'nameEn'=> "Uzbekistan" ],
    [ 'code'=> "VU", 'name'=> "فانواتو", 'nameEn'=> "Vanuatu" ],
    [ 'code'=> "VE", 'name'=> "فنزويلا", 'nameEn'=> "Venezuela (Bolivarian Republic of)" ],
    [ 'code'=> "VN", 'name'=> "فيتنام", 'nameEn'=> "Viet Nam" ],
    [ 'code'=> "VG", 'name'=> "جزر العذراء البريطانية", 'nameEn'=> "Virgin Islands (British)" ],
    [ 'code'=> "VI", 'name'=> "جزر العذراء الأمريكية", 'nameEn'=> "Virgin Islands (U.S.)" ],
    [ 'code'=> "WF", 'name'=> "واليس وفوتونا", 'nameEn'=> "Wallis and Futuna" ],
    [ 'code'=> "EH", 'name'=> "الصحراء الغربية", 'nameEn'=> "Western Sahara" ],
    [ 'code'=> "YE", 'name'=> "اليمن", 'nameEn'=> "Yemen" ],
    [ 'code'=> "ZM", 'name'=> "زامبيا", 'nameEn'=> "Zambia" ],
    [ 'code'=> "ZW", 'name'=> "زيمبابوي", 'nameEn'=> "Zimbabwe" ]
];