<?php

return [
    "education"              => "Education",
    "economics"              => "Economics",
    "medicine"               => "Medicine",
    "psychology"             => "Psychology",
    "sociology"              => "Sociology",
    "engineering"            => "Engineering",
    "computer_science"       => "Computer Science",
    "physics"                => "Physics",
    "chemistry"              => "Chemistry",
    "biology"                => "Biology",
    "mathematics"            => "Mathematics",
    "curriculum_instruction" => "Curriculum & Instruction",
    "humanities"             => "Humanities",
    "political_science"      => "Political Science",
    "arabic_language_literature" => "Arabic Language & Literature",
    "linguistics"            => "Linguistics",
    "islamic_studies"        => "Islamic Studies",
    "theology_sharia"        => "Theology & Sharia",
    "information_technology" => "Information Technology",
    "pharmacy"               => "Pharmacy & Pharmaceutical Sciences",
    "nursing_public_health"  => "Nursing & Public Health",
    "veterinary_medicine"    => "Veterinary Medicine",
    "agricultural_sciences"  => "Agricultural Sciences",
    "agribusiness"           => "Agribusiness & Agricultural Economics",
    "environmental_sciences" => "Environmental Sciences",
    "climate_change"         => "Climate Change & Sustainability",
    "business_admin"         => "Business Administration & Management",
    "finance_accounting"     => "Finance & Accounting",
    "law"                    => "Law & Legal Studies",
    "public_admin"           => "Public Administration & Policy",
    "risk_management"        => "Risk Management",
    "crisis_management"      => "Crisis Management",
    "disaster_studies"       => "Disaster Studies & Emergency Management",
    "general_science"        => "General Science & Multidisciplinary Research",
    "other"                  => "Other (not specified)",
];
